# Generated by Django 5.0.7 on 2024-08-04 21:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='birth_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
